In [1]:
import numpy as np
from numpy import poly

# Generate a random integer matrix C of size 4x3
C = np.random.randint(low=-10, high=10, size=(4, 3))

# Calculate A1 = C.T * C (Matrix multiplication of C transpose and C)
A1 = np.dot(C.T, C)

# Compute the eigenvalues and eigenvectors of A1
eigenvalues, eigenvectors = np.linalg.eig(A1)

# Compute the characteristic polynomial coefficients from the eigenvalues
char_poly_coefficients = poly(eigenvalues)

# Print the matrices, characteristic polynomial coefficients, eigenvalues, and eigenvectors
print("Matrix C:\n", C)
print("Matrix A1:\n", A1)
print("Characteristic polynomial coefficients:\n", char_poly_coefficients)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



Matrix C:
 [[ -3  -4  -1]
 [ -9   3 -10]
 [  0 -10  -7]
 [  9   0  -2]]
Matrix A1:
 [[171 -15  75]
 [-15 125  44]
 [ 75  44 154]]
Characteristic polynomial coefficients:
 [ 1.000000e+00 -4.500000e+02  5.917300e+04 -2.123919e+06]
Eigenvalues:
 [ 58.62589369 241.1301992  150.24390711]
Eigenvectors:
 [[ 0.51265048  0.70235368 -0.49385098]
 [ 0.55187654  0.17107643  0.8161894 ]
 [-0.65773989  0.69096466  0.2999101 ]]
